// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBTzJzFHyTvFUR9Gp1NUrrudNjvDT8qc',
    appId: '1:525491358598:web:50592aef8122f064a83a07',
    messagingSenderId: '525491358598',
    projectId: 'flutterproject-80401',
    authDomain: 'flutterproject-80401.firebaseapp.com',
    storageBucket: 'flutterproject-80401.appspot.com',
    measurementId: 'G-99V7Q8KHFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASuRjbiOd9xIFK5AhTr39NsUKtEFHncJs',
    appId: '1:525491358598:android:afd1ff6061d6fce2a83a07',
    messagingSenderId: '525491358598',
    projectId: 'flutterproject-80401',
    storageBucket: 'flutterproject-80401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSN3-6wBAMOL2o6HAq-jeohWXqPNY4EAE',
    appId: '1:525491358598:ios:fb40e708da2a28b9a83a07',
    messagingSenderId: '525491358598',
    projectId: 'flutterproject-80401',
    storageBucket: 'flutterproject-80401.appspot.com',
    iosClientId: '525491358598-gic00ukgp3fugijhm903iap00lr5rap0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSN3-6wBAMOL2o6HAq-jeohWXqPNY4EAE',
    appId: '1:525491358598:ios:fb40e708da2a28b9a83a07',
    messagingSenderId: '525491358598',
    projectId: 'flutterproject-80401',
    storageBucket: 'flutterproject-80401.appspot.com',
    iosClientId: '525491358598-gic00ukgp3fugijhm903iap00lr5rap0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
